### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by XNDIC** [LinWeizheDragon/FLMR#36]
FileNotFoundError: [Errno 2] **No such file or directory: 'F:/PreFLMR/FLMR/examples\\test_experiment\\indexes/test_index.nbits=8\\_metadata.json_'**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\PreFLMR\FLMR\examples\example_use_flmr.py", line 382, in <module>
    main(args)
  File "F:\PreFLMR\FLMR\examples\example_use_flmr.py", line 315, in main
    ds = query_index(args, ds, passage_contents, flmr_model)
  File "F:\PreFLMR\FLMR\examples\example_use_flmr.py", line 56, in query_index
    searcher = create_searcher(
  File "F:\PreFLMR\FLMR\flmr\searching.py", line 31, in create_searcher
    searcher = Searcher(
  File "F:\PreFLMR\FLMR\third_party\ColBERT\colbert\searcher.py", line 33, in __init__
    self.index_config = ColBERTConfig.load_from_index(self.index)
  File "F:\PreFLMR\FLMR\third_party\ColBERT\colbert\infra\config\base_config.py", line 85, in load_from_index
    loaded_config, _ = cls.from_path(metadata_path)
  File "F:\PreFLMR\FLMR\third_party\ColBERT\colbert\infra\config\base_config.py", line 42, in from_path
    with open(name) as f:
FileNotFoundError: [Errno 2] **No such file or directory: 'F:/PreFLMR/FLMR/examples\\test_experiment\\indexes/test_index.nbits=8\\_plan.json_'**

How can the above bug be solved? Where can I generate **plan.json and metadata.json**? What is the purpose of each?
Hope to get a reply, thanks!

**Comment by LinWeizheDragon** [comment]
I think this is caused by the different path format of Windows and Linux.
The path shown is illegal - 'F:/PreFLMR/FLMR/examples\test_experiment\indexes/test_index.nbits=8\metadata.json'

**The easiest solution is to run the program on Linux or on WSL2 of Windows.**

If you really want to run it on Windows, you can try to debug by checking the paths generated by the engine. It might be a careless use of path1 + "/" + path2 in the original ColBERT's engine. You may need to find these mistakes and replace them with os.path.join(path1, path2).

**Comment by XNDIC** [comment]
Thanks for the reply, the main problem I'm having is that I don't have the two json files mentioned above. Is there any solution for this?

**Comment by LinWeizheDragon** [comment]
I guess this is the same issue as this doesn't happen in Linux.
The ColBERT's engine generated the wrong path, resulting in errors when saving these index files. You won't be able to find these files as they could not be saved successfully.

**Comment by LinWeizheDragon** [comment]
By the way, did you successfully run the indexing process? Is there any error generated by the program? You can run with `--run_indexing` to force index re-generation and inspect if there is any issues when running the indexing process.
After successful indexing, you should have a folder similar to this:
![image](https://github.com/user-attachments/assets/e834b6de-06b3-4f27-9531-776e5f4bded9)
